name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/812211246549/locations/global/workloadIdentityPools/github-pool/providers/github-provider-v2"
          service_account: "github-ci-cd@smart-asset-control.iam.gserviceaccount.com"

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: smart-backend
          region: southamerica-east1
          source: ./backend
          allow-unauthenticated: true
          env_vars: PORT=3000