
name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: smart-asset-control
        service_account_email: github-ci-cd@smart-asset-control.iam.gserviceaccount.com
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy smart-backend           --source ./backend           --platform managed           --region southamerica-east1           --allow-unauthenticated           --port 3000
